[package]
name = "local-task"
version = "0.1.0"
edition = "2024"
authors = ["Jiangfeng Huang <paraworker@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Paraworker/local-task"
description = "A single-threaded async task model"

[dependencies]
slab = "0.4.11"
